### PR TITLE
Fix previews

### PR DESCRIPTION
**Pull request by jacobp100**
# I was not able to get the example running

* Ensures view flattening will not break this module in the future
* Tidy up inconsistent whitespace
* Make private property names match conventions

### CODE REVIEW

**Comment by mpiannucci** [comment]
Awesome thanks for this!! 

After these changes were you able to get the example running?

**Review by mpiannucci — APPROVED** [review]
Good stuff here, thanks for the attention to detail!

**Comment by jacobp100** [comment]
@mpiannucci I couldn’t get the example to run at all (even before the changes). Does your local setup work, and are you able to verify this works?

**Comment by mpiannucci** [comment]
Gotcha, it was working in my work laptop the other day but let me verify on another machine later today

**Comment by mpiannucci** [comment]
So a fresh clone works for me just fine: 

preview

**Comment by mpiannucci** [comment]
This branch works well too :)

**Comment by fukemy** [comment]
hi, does preview work for android?

**Comment by mpiannucci** [comment]
No, previews only work for iOS

**Pull request merged**
