### PR TITLE
Add disabled prop

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by mpiannucci** [comment]
Does this work in android too? Or just iOS

**Comment by jacobp100** [comment]
Just iOS. Probably not too hard to add for android. Can take a look when I get time

**Comment by mpiannucci** [comment]
Sounds good, in the meantime I can merge it if you just add a note it's iOS only in the documentation

**Comment by jacobp100** [comment]
Sorry for the delay. Done

**Review by mpiannucci — APPROVED** [review]

**Comment by mpiannucci** [comment]
Thanks! I'll get an update out soon

**Pull request merged**
