### PR TITLE
Use clear background color for preview

### PR DESCRIPTION
**Pull request by mrousavy**
Fixes my comments mentioned in #11, but not the actual issue itself.

<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td width="50%">

</td>
<td>

</td>
</tr>
</table>

### CODE REVIEW

**Comment by mrousavy** [comment]
Also, the source code might be happy about a little cleanup and formatting. 😄

**Comment by mrousavy** [comment]
I couldn't manage to get it working if there are different border radii though, this might be able to work with a layer mask... 🤔

**Comment by jacobp100** [comment]
This looks really good!

What do you think about doing this via a `backgroundColor` property? My concerns are firstly this is this is probably a breaking change, and also people might want to customise it.

Let me know if you need any pointers

**Comment by mpiannucci** [comment]
I like this change for now @mrousavy thank you. 

I think the eventual final form of this to allow for a completely custom preview view but for now this is great. Merging!

**Comment by mrousavy** [comment]
I'll create a PR which supports using custom a `backgroundColor` tomorrow. I'm still not sure on how to tackle the multiple/different border radii problem though...

**Comment by jacobp100** [comment]
@mrousavy Just a note that you'll need to set `previewBackgroundColor="transparent"` for your use-case as of #19

**Comment by mrousavy** [comment]
yes, saw that! thank you! It's still bugging me that the different border radii are not supported 😭

**Pull request merged**
